default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: <%= ENV['DATABASE_PORT'].to_i %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

